# Generated by Django 3.0.1 on 2021-08-01 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBJETSITE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Consolidé'), ('2', 'Pole'), ('3', 'Société'), ('4', 'Direction'), ('5', 'Sous-direction'), ('6', 'Rapport')], default='1', max_length=1)),
                ('nom', models.CharField(default='', max_length=80)),
                ('lien', models.CharField(blank=True, max_length=500, null=True)),
                ('slider', models.BooleanField(default=False)),
                ('lienaut', models.CharField(blank=True, max_length=500, null=True)),
                ('liensup', models.CharField(blank=True, max_length=500, null=True)),
                ('ancetrenom', models.CharField(blank=True, max_length=100, null=True)),
                ('ancetretype', models.CharField(blank=True, max_length=1, null=True)),
                ('champsbdd', models.CharField(blank=True, max_length=1000, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.OBJETSITE')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pagenom', models.CharField(blank=True, default='', max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinconnu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.CharField(blank=True, default='', max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('poste', models.CharField(blank=True, max_length=160, null=True)),
                ('slider', models.BooleanField(default=False)),
                ('type_autorisation', models.CharField(choices=[('TC', 'Consolidé (tous)'), ('AU', 'Autre')], default='AU', max_length=2)),
                ('admin', models.BooleanField(default=False)),
                ('droitauth', models.BooleanField(default=False)),
                ('photo', models.TextField(blank=True)),
                ('id_objet', models.ManyToManyField(blank=True, related_name='id_objet', to='Login.OBJETSITE')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societe', to='Login.OBJETSITE')),
                ('superieur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superieur', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HISTORIQUELOGIN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateurid', models.PositiveIntegerField()),
                ('typepageid', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('temps', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('typepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='contenttypes.ContentType')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='contenttypes.ContentType')),
            ],
        ),
    ]
