# Generated by Django 3.0.1 on 2022-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetsite',
            name='champsbdd',
        ),
        migrations.RemoveField(
            model_name='objetsite',
            name='lienaut',
        ),
        migrations.RemoveField(
            model_name='objetsite',
            name='liensup',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='droitauth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='societe',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
