# Generated by Django 3.0.1 on 2022-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20220226_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetsite',
            name='type',
            field=models.CharField(choices=[('1', 'Consolidé'), ('2', 'Pole'), ('3', 'Région'), ('4', 'Direction'), ('5', 'Sous-direction'), ('6', 'Rapport')], default='1', max_length=1),
        ),
    ]
