# Generated by Django 3.0.1 on 2021-08-01 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requette',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('texteliens', models.TextField()),
                ('texteutilisateur', models.TextField()),
                ('texteact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('listerapport', models.ManyToManyField(blank=True, related_name='listerapport', to='Login.OBJETSITE')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userslider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(max_length=120)),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('couleur', models.CharField(choices=[('1', 'Recue'), ('2', 'En-cours'), ('3', 'Validation'), ('4', 'Confirmation')], default='#2E538B', max_length=7)),
                ('recu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messagerie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('sujet', models.CharField(default='', max_length=80)),
                ('probleme', models.TextField(default='')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('lien', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeProbleme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Recue'), ('2', 'En-cours'), ('3', 'Validation'), ('4', 'Confirmation')], default='1', max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('messagerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.Messagerie')),
            ],
        ),
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('1', 'Ajouter'), ('2', 'Supprimer')], default='1', max_length=7)),
                ('useract', models.CharField(max_length=60)),
                ('dateact', models.DateTimeField(auto_now_add=True)),
                ('validite', models.BooleanField(default=False)),
                ('refuser', models.BooleanField(default=False)),
                ('userchoix', models.CharField(max_length=60)),
                ('objetsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.OBJETSITE')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
