from django.urls import path

from bi import views

urlpatterns = [
    path('', views.home, name='cbi'),
    path('home', views.home, name='home'),
    path('apropos', views.pageapropos, name='apropos'),
    path('accueil', views.acceuilpage, name='accueil'),
    path('adminpage', views.adminpage, name='adminpage'),
    path('parent', views.parent, name='parent'),
    path('messagerie', views.messagerieAdmin, name='messagerie'),
    path('recherchemsg', views.recherchemessagerieelem, name='recherchemsg'),
    path('authadmin', views.adminauth, name='authadmin'),
    path('authcom', views.adminelse, name='authcom'),
    path('ajoutimage', views.ajoutimagemessagerie, name='ajoutimage'),
    path('information/<int:pk>', views.informationmessage, name='information'),
    path('rapport/<int:pk>', views.homerap, name='information'),
    path('getchildsdash', views.tableaudebordenfs, name='getchildsdash'),
    path('page/<str:pk>', views.homepage, name='information'),
    path('authuser/<int:pk>', views.loadauthuser, name='authuser'),
    path('delauth', views.suppressionauth, name='delauth'),
    path('getchilds', views.getchildsofobjsite, name='getchilds'),
    path('newauth', views.nouveauautuser, name='newauth'),
    path('authact', views.actionautorisation, name='authact'),
    path('parentchoix', views.newparentchoixe, name='parentchoix'),
    path('parentf', views.parentfinal, name='parentf'),
    path('chargementrapport/<int:pk>', views.loadurlbyid, name='chargementrapport'),
    path('userhistory', views.historiqueutil, name='userhistory'),
    path('statadmin', views.StatistiqueAdmin, name='statadmin'),
    path('verifierutilauth', views.verifierutilisateurfroit, name='verifierutilauth'),
    path('historique', views.historypage, name='historique'),
    path('slider', views.sliderpage, name='slider'),
    path('lanceslider', views.playslider, name='lanceslider'),
    path('sliderinfo/<int:pk>', views.informationslider, name='sliderinfo'),
    path('sliderlancement/<int:pk>', views.lancementduslider, name='sliderlancement'),
    path('delslider/<int:pk>', views.slidersuppression, name='delslider'),
    path('urlrapport/<int:pk>', views.strlienrap, name='urlrapport'),
    path('changementtempshisto', views.histochangetimenew, name='changementtempshisto'),
    ]
